### PR TITLE
BLD: switch bluesky dep to bluesky-base

### PR DESCRIPTION
**Pull request by ZLLentz**
This avoids pulling in additional unused or optional sub-dependencies by default.
It's a small detail we've been updating in some of our other feedstocks that we missed when creating this one.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] ~Reset the build number to `0` (if the version changed)~
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ZLLentz** [comment]
@conda-forge-admin, please rerender

**Comment by ZLLentz** [comment]
previous rerender error was a server error, retrying after latest unrelated commit
we messed up the original maintainers on this repo in https://github.com/conda-forge/staged-recipes/pull/27370 so we'll need to ask for some help

**Comment by ZLLentz** [comment]
@conda-forge-admin, please rerender

**Comment by tangkong** [comment]
@conda-forge-admin, please update team

**Comment by ZLLentz** [comment]
To simplify things, I will:
- close this PR
- rebase
- open a new PR

**Comment by ZLLentz** [comment]
superseded by #4

**Pull request closed without merging**
